In [1]:
import pandas as pd
import numpy as np

In [25]:
df=pd.read_csv('cleaner.csv')

In [26]:
df.head()

Unnamed: 0                       Consumer_complaint_narrative  \
0           0                          remove fraud alert equifa   
1           1  hard pull made credit report said credit repor...   
2           2  year property ta due realized one mortgage esc...   
3           3  made settlement offer  three payment satisfied...   
4           4  challenged account shown credit month link pro...   

                                             Product  
0  Credit reporting, credit repair services, or o...  
1  Credit reporting, credit repair services, or o...  
2  Credit reporting, credit repair services, or o...  
3  Credit reporting, credit repair services, or o...  
4  Credit reporting, credit repair services, or o...

In [5]:
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [27]:
X_train,X_test,y_train,y_test=train_test_split(df['Consumer_complaint_narrative'],df['Product'],test_size=0.3,random_state=68)

In [28]:
from sklearn.pipeline import Pipeline

In [29]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
#vectorizer=TfidfVectorizer()

In [34]:
X_train=X_train.astype(str)

In [38]:
text=Pipeline([('tfidf',TfidfVectorizer()),('classifier',RandomForestClassifier(n_estimators=100))])

In [39]:
text.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('classifier', RandomForestClassifier())])

In [40]:
predictions=text.predict(X_test)

In [41]:
from sklearn.metrics import confusion_matrix,classification_report

In [42]:
print(confusion_matrix(y_test,predictions))

[[4789  323   74   49  640   54   33   11   30]
 [ 506 4644  272  156  211   44   44   44   89]
 [  40  239 4800  399   14  123   23  117  200]
 [  72  193  535 4632   32  128   92  113  125]
 [ 537  119   29   39 5213   38   24   14   13]
 [  76   49   77   57   23 5590  107   49   49]
 [ 130   97  133  201   85   94 4908   74  205]
 [  23   46  109  118   22   64  143 5467   43]
 [  44  120  227  124   22   63  169   47 5229]]


In [43]:
print(classification_report(y_test,predictions))

                                                                              precision    recall  f1-score   support

                                                 Checking or savings account       0.77      0.80      0.78      6003
                                                 Credit card or prepaid card       0.80      0.77      0.78      6010
Credit reporting, credit repair services, or other personal consumer reports       0.77      0.81      0.79      5955
                                                             Debt collection       0.80      0.78      0.79      5922
                          Money transfer, virtual currency, or money service       0.83      0.87      0.85      6026
                                                                    Mortgage       0.90      0.92      0.91      6077
                                   Payday loan, title loan, or personal loan       0.89      0.83      0.86      5927
                                                       

In [44]:
from sklearn import metrics

In [45]:
metrics.accuracy_score(y_test,predictions)

0.8383703703703703

In [73]:
rf_1=Pipeline([('tfidf',TfidfVectorizer()),('classifier',RandomForestClassifier(n_estimators=500))])

In [74]:
rf_1.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('classifier', RandomForestClassifier(n_estimators=500))])

In [80]:
predict_2=rf_1.predict(X_test)

In [82]:
print(confusion_matrix(y_test,predict_2))

[[4882  300   79   41  578   56   32   10   25]
 [ 439 4776  269  157  178   40   37   39   75]
 [  44  233 4797  384   18  121   18  122  218]
 [  70  198  516 4642   30  127   90  111  138]
 [ 508  117   34   35 5244   36   26   16   10]
 [  58   49   73   49   28 5639   98   43   40]
 [ 110   95  132  200   77   90 4980   50  193]
 [  20   40  105  105   23   48  132 5520   42]
 [  35  106  223  120   23   54  141   41 5302]]


In [83]:
print(classification_report(y_test,predict_2))

                                                                              precision    recall  f1-score   support

                                                 Checking or savings account       0.79      0.81      0.80      6003
                                                 Credit card or prepaid card       0.81      0.79      0.80      6010
Credit reporting, credit repair services, or other personal consumer reports       0.77      0.81      0.79      5955
                                                             Debt collection       0.81      0.78      0.80      5922
                          Money transfer, virtual currency, or money service       0.85      0.87      0.86      6026
                                                                    Mortgage       0.91      0.93      0.92      6077
                                   Payday loan, title loan, or personal loan       0.90      0.84      0.87      5927
                                                       

In [85]:
metrics.accuracy_score(y_test,predict_2)

0.8478148148148148

In [87]:
rf_3=Pipeline([('tfidf',TfidfVectorizer()),('classifier',RandomForestClassifier(n_estimators=1000))])

In [ ]:
rf_3.fit(X_train,y_train)

In [20]:
#X_train=vectorizer.fit_transform(X_train)

In [21]:
from sklearn.model_selection import GridSearchCV

In [22]:
#param_grid={'n_estimators':[50,100,200,300]}


In [23]:
#rf=RandomForestClassifier()
gridsearch=GridSearchCV(estimator=rf,param_grid=param_grid)

In [1]:
#gridsearch.fit(X_train,y_train)

In [47]:
from xgboost import XGBClassifier

In [50]:
xgb=Pipeline([('tfidf',TfidfVectorizer()),('classifier',XGBClassifier(n_estimators=100))])

In [51]:
xgb.fit(X_train,y_train)

/home/ubuntu/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[19:02:25] WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('classifier',
                 XGBClassifier(base_score=0.5, booster='gbtree',
                               colsample_bylevel=1, colsample_bynode=1,
                               colsample_bytree=1, gamma=0, gpu_id=-1,
                               importance_type='gain',
                               interaction_constraints='',
                               learning_rate=0.300000012, max_delta_step=0,
                               max_depth=6, min_child_weight=1, missing=nan,
                               monotone_constraints='()', n_estimators=100,
                               n_jobs=4, num_parallel_tree=1,
                               objective='multi:softprob', random_state=0,
                               reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
                               subsample=1, tree_method='exact',
                               validate_parameters=1, verbosity=None))])

In [52]:
xgb_predict=xgb.predict(X_test)

In [53]:
print(confusion_matrix(y_test,xgb_predict))

[[4844  316   47   43  562   46  105    7   33]
 [ 323 4923  208  162  152   24  123    7   88]
 [  59  262 4649  412   14  100  101  124  234]
 [  77  190  511 4603   32   96  185   99  129]
 [ 657  175   20   48 4931   46  102   21   26]
 [  43   34   72   49   25 5551  220   29   54]
 [ 162  131  158  276  101  121 4567   42  369]
 [  18   29   88   99   17   32  349 5323   80]
 [  39  113  202  137   21   34  392   14 5093]]


In [54]:
print(classification_report(y_test,xgb_predict))

                                                                              precision    recall  f1-score   support

                                                 Checking or savings account       0.78      0.81      0.79      6003
                                                 Credit card or prepaid card       0.80      0.82      0.81      6010
Credit reporting, credit repair services, or other personal consumer reports       0.78      0.78      0.78      5955
                                                             Debt collection       0.79      0.78      0.78      5922
                          Money transfer, virtual currency, or money service       0.84      0.82      0.83      6026
                                                                    Mortgage       0.92      0.91      0.92      6077
                                   Payday loan, title loan, or personal loan       0.74      0.77      0.76      5927
                                                       

In [55]:
metrics.accuracy_score(y_test,xgb_predict)

0.8237777777777778

In [56]:
xgb_1=Pipeline([('tfidf',TfidfVectorizer()),('classifier',XGBClassifier(n_estimators=200))])

In [57]:
xgb_1.fit(X_train,y_train)

/home/ubuntu/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[20:18:28] WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('classifier',
                 XGBClassifier(base_score=0.5, booster='gbtree',
                               colsample_bylevel=1, colsample_bynode=1,
                               colsample_bytree=1, gamma=0, gpu_id=-1,
                               importance_type='gain',
                               interaction_constraints='',
                               learning_rate=0.300000012, max_delta_step=0,
                               max_depth=6, min_child_weight=1, missing=nan,
                               monotone_constraints='()', n_estimators=200,
                               n_jobs=4, num_parallel_tree=1,
                               objective='multi:softprob', random_state=0,
                               reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
                               subsample=1, tree_method='exact',
                               validate_parameters=1, verbosity=None))])

In [58]:
xgb_predict_1=xgb_1.predict(X_test)

In [78]:
print(confusion_matrix(y_test,xgb_predict_1))

[[4880  304   47   44  551   47   95    6   29]
 [ 318 4960  201  158  139   26  106   19   83]
 [  56  245 4720  401   12   94   88  122  217]
 [  85  189  476 4643   28   93  182   99  127]
 [ 617  172   19   42 4986   43  101   21   25]
 [  48   34   77   43   22 5592  178   27   56]
 [ 133  124  134  251   85  104 4739   38  319]
 [  16   31   95   94   18   32  281 5418   50]
 [  33  107  199  131   20   27  357   27 5144]]


In [61]:
metrics.accuracy_score(y_test,xgb_predict_1)

0.8348518518518518

In [62]:
X_train_1=vectorizer.fit_transform(X_train)

In [63]:
param_grid={'n_estimators':[300,500]}

In [64]:
x=XGBClassifier()
gridsearch=GridSearchCV(estimator=x,param_grid=param_grid)

In [2]:
#gridsearch.fit(X_train_1,y_train)

In [66]:
xgb_2=Pipeline([('tfidf',TfidfVectorizer()),('classifier',XGBClassifier(n_estimators=500))])

In [67]:
xgb_2.fit(X_train,y_train)

/home/ubuntu/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[07:39:35] WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('classifier',
                 XGBClassifier(base_score=0.5, booster='gbtree',
                               colsample_bylevel=1, colsample_bynode=1,
                               colsample_bytree=1, gamma=0, gpu_id=-1,
                               importance_type='gain',
                               interaction_constraints='',
                               learning_rate=0.300000012, max_delta_step=0,
                               max_depth=6, min_child_weight=1, missing=nan,
                               monotone_constraints='()', n_estimators=500,
                               n_jobs=4, num_parallel_tree=1,
                               objective='multi:softprob', random_state=0,
                               reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
                               subsample=1, tree_method='exact',
                               validate_parameters=1, verbosity=None))])

In [68]:
xgb_predict_2=xgb_2.predict(X_test)

In [69]:
print(confusion_matrix(y_test,xgb_predict_2))

[[4911  312   43   38  539   44   81    8   27]
 [ 318 4983  206  152  137   26   91   21   76]
 [  51  246 4736  408    9   91   80  124  210]
 [  73  181  449 4717   24   91  161   98  128]
 [ 557  158   17   38 5090   38   90   21   17]
 [  49   41   79   53   17 5613  132   33   60]
 [ 101   92  104  188   71   77 4970   33  291]
 [  16   35   96   92   15   31  234 5467   49]
 [  25   99  188  126   15   26  294   30 5242]]


In [86]:
print(classification_report(y_test,xgb_predict_2))

                                                                              precision    recall  f1-score   support

                                                 Checking or savings account       0.80      0.82      0.81      6003
                                                 Credit card or prepaid card       0.81      0.83      0.82      6010
Credit reporting, credit repair services, or other personal consumer reports       0.80      0.80      0.80      5955
                                                             Debt collection       0.81      0.80      0.80      5922
                          Money transfer, virtual currency, or money service       0.86      0.84      0.85      6026
                                                                    Mortgage       0.93      0.92      0.93      6077
                                   Payday loan, title loan, or personal loan       0.81      0.84      0.82      5927
                                                       

In [70]:
metrics.accuracy_score(y_test,xgb_predict_2)

0.8468333333333333